### ISSUE TITLE
Wrong number of shells in ShellArray

### ISSUE THREAD

**Issue by bwvdnbro** [jchelly/LightconeIO#1]
I got an error when trying to read one of the FLAMINGO lightcones. Turns out the number of shells read in by `ShellArray` is wrong:

https://github.com/jchelly/LightconeIO/blob/9ca5475e6844a8303afe418be611efe9e2578751/lightcone_io/healpix_maps.py#L198

This should read the `nr_shells` attribute rather than the `nr_files_per_shell` attribute.

**Comment by jchelly** [comment]
Thanks for spotting that. I've pushed an update to master that should fix it.
