### ISSUE TITLE
No units in read_exact output

### ISSUE THREAD

**Issue by Eusrace** [jchelly/LightconeIO#2]
I found that there is no unit in output of .read_exact in particle_reader, but there are units in output of .read.

when using .read_exact attribute:
'Velocities': unyt_array([[ 146.23571777,  -13.46435547,  399.93579102],
            [ 190.63574219, -273.96435547,  -41.36425781],
            [ 368.13574219, -439.56433105,   84.53564453],
            ...,
            [-107.8815918,  250.71838379, -590.18157959],
            [-181.28161621,  -18.98156738, -304.08154297],
            [-351.68164062, -238.28161621, -597.18157959]], dtype=float32, units='dimensionless')}

when using .read attribute:
unyt_array([[-558.8482666, -132.74829102,  -46.44824219],
            [-542.14831543, -125.24829102,  -27.04821777],
            [-559.8482666,  -99.44824219,  -62.74829102],
            ...,
            [ 272.18530273, -327.61474609,  162.28527832],
            [ 288.28527832, -346.61474609,  171.58532715],
            [ 298.68530273, -234.21472168,  171.38525391]], dtype=float32, units='100000*cm/s')},

**Comment by jchelly** [comment]
Thanks for the bug report. The read_exact() method does some extra filtering so I think something there must be stripping the units, although I'm surprised you get a dimensionless unyt_array rather than just a numpy array if that's the case. I'll take a look.

**Comment by jchelly** [comment]
Ok, I think I found the problem: numpy.concatenate() strips the units from unyt arrays! That seems like it must be a bug in either unyt or numpy. I'll have to write my own concatenate function.

**Comment by jchelly** [comment]
unyt provides its own concatenate function, so I've used that. I think it should work now.

**Comment by Eusrace** [comment]
Thank you very much!
