### ISSUE TITLE
unit bug in smoothing code?

### ISSUE THREAD

**Issue by Eusrace** [jchelly/LightconeIO#3]
Hi John,

I think perhaps there is a bug about units in make_full_sky_map function?
The only thing I have altered is constrain a certain region of the sky...
Would you please have a look at it if you have time? Thanks a lot! :D

Best regards,
Yanling

And the following is the bug report
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   login8a
  Local device: mlx5_0
--------------------------------------------------------------------------
Total number of pixels = 3221225472
Total number of particles = 3395870763
Read in particle data
Traceback (most recent call last):
  File "/cosma8/data/dp004/dc-chen3/bin/smooth_lc.py", line 35, in <module>
    L1000N1800_HYDRO_FIDUCIAL_smoothed_gas_mass()
  File "/cosma8/data/dp004/dc-chen3/bin/smooth_lc.py", line 27, in L1000N1800_HYDRO_FIDUCIAL_smoothed_gas_mass
    map_data = smoothed_map.make_full_sky_map(input_filename, ptype, property_names, particle_mass,
  File "/cosma/home/dp004/dc-chen3/.local/lib/python3.10/site-packages/lightcone_io/smoothed_map.py", line 274, in make_full_sky_map
    map_units = part_val_send.units
AttributeError: 'numpy.ndarray' object has no attribute 'units'

The following is the smooth_lc.py, i just python3 smooth_lc.py
--------------------------------------
import numpy as np
import h5py
import lightcone_io.smoothed_map as smoothed_map
import virgo.mpi.parallel_hdf5 as phdf5

from mpi4py import MPI
comm = MPI.COMM_WORLD

def L1000N1800_HYDRO_FIDUCIAL_smoothed_gas_mass():
    nside = 16384
    input_filename = "/cosma8/data/dp004/jch/FLAMINGO/ScienceRuns/L1000N1800/HYDRO_FIDUCIAL/lightcones/lightcone0_particles/lightcone0_0000.0.hdf5"
    output_filename = "/cosma7/data/dp004/dc-chen3/new_maps/smoothed_gas_map.hdf5"
    vector = np.array([-218.7715541,-41.9186541,-26.6967541])
    radius = 5
    zmin, zmax = (0, 0.1)
    ptype = "Gas"
    property_names = ("Masses",)

    # Function to return the quantity to map, given the lightcone particle data dict
    def particle_mass(particle_data):
        return particle_data["Masses"]

    dataset_name = "SmoothedGasMass"

    # Make the map
    map_data = smoothed_map.make_full_sky_map(input_filename, ptype, property_names, particle_mass,
                                                zmin, zmax, nside, smooth=True, progress=True)

    # Write out the new map
    with h5py.File(output_filename, "w", driver="mpio", comm=comm) as outfile:
        phdf5.collective_write(outfile, dataset_name, map_data, comm)

if __name__ == "__main__":
    L1000N1800_HYDRO_FIDUCIAL_smoothed_gas_mass()
    #test_bh_map()

**Comment by bwvdnbro** [comment]
I was just going to report the same issue.

The problem is `smoothed_map.py:270`:
```
    part_val_send = np.asarray(particle_value_function(particle_data), dtype=float)
```
which turns `part_val_send` into an ordinary `numpy.array`. To fix the issue, you need to change `smoothed_map.py:274` from
```
    map_units = part_val_send.units
```
to
```
    map_units = particle_value_function(particle_data).units
```
That did the trick for me.

**Comment by bwvdnbro** [comment]
There were some additional issues down the line. This is what I had to change to make it work:
```
diff --git a/lightcone_io/smoothed_map.py b/lightcone_io/smoothed_map.py
index 2771965..99c961a 100644
--- a/lightcone_io/smoothed_map.py
+++ b/lightcone_io/smoothed_map.py
@@ -271,7 +269,8 @@ def make_full_sky_map(input_filename, ptype, property_names, particle_value_func
     val_total_global = comm.allreduce(np.sum(part_val_send, dtype=float))
 
     # Find units of the quantity which we're mapping
+    map_units = particle_value_function(particle_data).units
     all_map_units = comm.allgather(map_units)
     for unit in all_map_units:
         if unit != map_units:
@@ -347,7 +346,7 @@ def make_full_sky_map(input_filename, ptype, property_names, particle_value_func
                                            part_pos_recv.value[single_pixel, 1],
                                            part_pos_recv.value[single_pixel, 2]) - local_offset
     local = (local_pix_index >=0) & (local_pix_index < nr_local_pixels)
-    np.add.at(map_view, local_pix_index[local], part_val_recv[single_pixel][local].value)
+    np.add.at(map_view, local_pix_index[local], part_val_recv[single_pixel][local])
     message("Applied single pixel updates")
     
     # Discard single pixel particles
@@ -357,8 +356,8 @@ def make_full_sky_map(input_filename, ptype, property_names, particle_value_func
 
     # Apply updates from particles which cover multiple pixels.
     nr_parts = len(part_val_recv)
-    part_pos_view  = part_pos_recv.ndarray_view()
-    part_val_view  = part_val_recv.ndarray_view()
+    part_pos_view  = part_pos_recv.view()
+    part_val_view  = part_val_recv.view()
     for part_nr in progress_bar(range(nr_parts)):
         pix_index, pix_val = explode_particle(nside, part_pos_view[part_nr,:], part_val_view[part_nr], part_hsml_recv
         local_pix_index = pix_index - local_offset
```
The script is still running, so there could be more issues. But at least now I got to the bit with the progress bar.

**Comment by jchelly** [comment]
Thanks Bert. I read some advice in the unyt documentation about optimizing by stripping the units during calculations and reapplying them afterwards and I think I've broken a few things trying to do that.

**Comment by Eusrace** [comment]
Great, thanks!
